name: Scrape BCV Data

on:
  schedule:
    - cron: '0 */3 * * *'  # Cada 3 horas
  workflow_dispatch:      # Permite ejecución manual

jobs:
  scrape:
    runs-on: ubuntu-latest
    permissions:
      contents: write    # Permiso necesario para subir los JSON al repo

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run scraper
        run: python cli_scraper.py

      - name: Commit and push changes
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated update of BCV data [skip ci]"
          file_pattern: 'api/v1/*.json'
